[phases.setup]
nixPkgs = [
  "nodejs_20",
  "ffmpeg",
  "pkg-config",
  "cairo",
  "pango",
  "libpng",
  "libjpeg",
  "giflib",
  "librsvg",
  "pixman",
  "python3",
  "git",
  "openssh",
  "gcc",
  "gnumake"
]

[phases.install]
cmds = ["PUPPETEER_SKIP_DOWNLOAD=true PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true npm install --legacy-peer-deps"]

[start]
cmd = "node index.js"
