const mumaker = require('mumaker');
const config = require('../../config');

module.exports = {
  name: 'carbon',
  aliases: [],
  category: 'textmaker',
  description: 'Create carbon text effect',
  usage: '.carbon <text>',
  
  async execute(sock, msg, args) {
    try {
      const text = args.join(' ');
      const chatId = msg.key.remoteJid;
      
      if (!text) {
        return await sock.sendMessage(chatId, { 
          text: 'Please provide text to generate\nExample: .carbon Nick' 
        }, { quoted: msg });
      }
      
      const result = await mumaker.ephoto('https://en.ephoto360.com/carbon-text-effect-online-free-792.html', text);
      
      if (!result || !result.image) {
        throw new Error('No image URL received from the API');
      }
      
      await sock.sendMessage(chatId, {
        image: { url: result.image },
        caption: `GENERATED BY ${config.botName}`
      }, { quoted: msg });
      
    } catch (error) {
      console.error('Error in carbon command:', error);
      await sock.sendMessage(msg.key.remoteJid, { 
        text: `Error: ${error.message}` 
      }, { quoted: msg });
    }
  }
};
