/**
 * Language Manager — English (en) + Sinhala (si) + Urdu/Pakistan (pk)
 * Per-chat preference stored in memory (persists for session lifetime).
 */

const chatLangMap = new Map();

const LANGUAGES = {
  en: { name: 'English',  flag: '🇬🇧', label: 'English' },
  si: { name: 'සිංහල',   flag: '🇱🇰', label: 'Sinhala'  },
  pk: { name: 'اردو',    flag: '🇵🇰', label: 'Urdu'     },
};

const STRINGS = {
  en: {
    // Main menu
    user:        'User',
    owner:       'Owner',
    prefix:      'Prefix',
    commands:    'Commands',
    uptime:      'Uptime',
    ram:         'RAM',
    categories:  'CATEGORIES',
    tapBtn:      'Tap a button below to explore commands',
    cmdReady:    'commands ready',
    // Category titles
    cat_media:   'Media & Downloads',
    cat_admin:   'Admin Commands',
    cat_owner:   'Owner Commands',
    cat_tools:   'Tools & AI',
    cat_general: 'General & Fun',
    // Category labels (shown inside menu)
    cat_label_media:  'Media & Download',
    cat_label_admin:  'Group Admin',
    cat_label_owner:  'Owner Only',
    cat_label_tools:  'Tools & AI',
    cat_label_fun:    'Fun & General',
    // Submenu
    backMenu:    '🔙 Back to Menu',
    // Lang command
    currentLang: 'Current language',
    selectLang:  'Select your language',
    langChanged: 'Language changed to',
    langInvalid: 'Invalid. Use: .lang en, .lang si  or  .lang pk',
    // Menu section text
    menu_bot_status:  'BOT STATUS',
    menu_total:       'Total',
    menu_cmds:        'commands',
    menu_tap:         '💡 Tap a button below to view commands',
    menu_type_help:   '🔖 Type `{prefix}<command>` for usage help',
    cmds_available:   'commands available',
    send_cmd_usage:   'Send any command to get usage details',
    // Greetings
    greeting_morning:   '🌅 Good Morning',
    greeting_afternoon: '☀️ Good Afternoon',
    greeting_evening:   '🌙 Good Evening',
    // Alive command
    alive_greeting_1: 'Hey there! I am alive and kicking! 🚀',
    alive_greeting_2: 'Yes, I am online and ready to serve! ⚡',
    alive_greeting_3: 'I am up and running smoothly! 🌟',
    alive_greeting_4: 'Bot is alive and working perfectly! 💫',
    alive_greeting_5: 'Hello! I am here and active! 🎯',
    alive_status:     'STATUS',
    alive_online:     'Online',
    alive_status_lbl: 'Status',
    alive_uptime:     'Uptime',
    alive_owner:      'Owner',
    alive_prefix:     'Prefix',
    alive_version:    'Version',
    alive_type_menu:  'Type {prefix}menu to see all commands',
    alive_footer:     'What would you like to do?',
    alive_btn_menu:   '📋 Main Menu',
    alive_btn_ping:   '🏓 Test Ping',
    // Ping command
    ping_title:     'Infinity MD STATUS',
    ping_local:     'Local',
    ping_net:       'Net',
    ping_response:  'Response',
    ping_active:    'Active',
    ping_fast:      'FAST',
    ping_normal:    'NORMAL',
    ping_uptime:    'Uptime',
    ping_ram:       'RAM',
    ping_heap:      'Heap',
    ping_os:        'OS',
    ping_node:      'Node',
    ping_version:   'Version',
    ping_working:   '✨ Everything working perfectly!',
    ping_footer:    'Server Health',
    ping_btn_again: '🔄 Ping Again',
    ping_btn_menu:  '📋 Menu',
    // Runtime command
    runtime_title:      'RUNTIME INFO',
    runtime_bot_uptime: 'Bot Uptime',
    runtime_sys_uptime: 'System Uptime',
    runtime_bot_mem:    'Bot Memory',
    runtime_sys_mem:    'System Memory',
    runtime_cpu:        'CPU',
    runtime_cores:      'Cores',
    runtime_used:       'Used',
    runtime_free:       'Free',
    runtime_external:   'External',
    runtime_hostname:   'Hostname',
    // Owner command
    owner_title:    'OWNER INFO',
    owner_name:     'Name',
    owner_number:   'Number',
    owner_github:   'Github',
    // ── Command labels (2-3 words) ──
    song:         'Song download',
    yt:           'YouTube search',
    tiktok:       'TikTok download',
    ytmp3:        'YouTube → MP3',
    ytmp4:        'YouTube → MP4',
    play:         'Quick play',
    lyrics:       'Song lyrics',
    movie:        'Movie finder',
    antilink:     'Block links',
    demote:       'Remove admin',
    goodbye:      'Leave message',
    hidetag:      'Silent mention',
    kick:         'Kick member',
    lock:         'Lock group',
    members:      'List members',
    mute:         'Mute group',
    promote:      'Make admin',
    setname:      'Rename group',
    tagall:       'Tag everyone',
    unlock:       'Unlock group',
    unmute:       'Unmute group',
    warn:         'Warn member',
    welcome:      'Join message',
    anticall:     'Block calls',
    antidelete:   'Catch deletes',
    antiviewonce: 'Save viewonce',
    autoreact:    'Auto react',
    autoreply:    'Auto reply',
    autostatus:   'Auto status',
    block:        'Block user',
    broadcast:    'Mass message',
    join:         'Join group',
    leave:        'Leave group',
    mode:         'Bot mode',
    settings:     'Bot settings',
    unblock:      'Unblock user',
    ai:           'AI chat',
    gpt:          'GPT chat',
    calc:         'Calculator',
    sticker:      'Make sticker',
    translate:    'Translate text',
    weather:      'Weather info',
    wiki:         'Wikipedia',
    togif:        'Video → GIF',
    toimg:        'Sticker → image',
    tomp3:        'Video → MP3',
    fact:         'Random fact',
    joke:         'Random joke',
    meme:         'Random meme',
    alive:        'Bot status',
    ping:         'Ping bot',
    runtime:      'System stats',
    lang:         'Change language',
    save:         'Save status media',
    // ── Command descriptions (shown in menu) ──
    desc_movie:       'Sinhalasub.lk movies 🎬',
    desc_song:        'Download songs 🎵',
    desc_yt:          'YouTube info & search 🔍',
    desc_ytmp3:       'YouTube → MP3 🎧',
    desc_ytmp4:       'YouTube → MP4 📹',
    desc_play:        'Play & send audio ▶️',
    desc_tiktok:      'TikTok downloader 🎵',
    desc_lyrics:      'Search song lyrics 🎤',
    desc_film2:       'CineSubz movies & TV shows 🎬',
    desc_antilink:    'Block group invite links 🔗',
    desc_tagall:      'Tag all members 📢',
    desc_hidetag:     'Silent tag everyone 🔕',
    desc_kick:        'Remove a member 🦶',
    desc_promote:     'Promote to admin ⬆️',
    desc_demote:      'Remove admin role ⬇️',
    desc_mute:        'Mute the group 🔇',
    desc_unmute:      'Unmute the group 🔊',
    desc_lock:        'Lock group settings 🔒',
    desc_unlock:      'Unlock group settings 🔓',
    desc_welcome:     'Welcome new members 👋',
    desc_goodbye:     'Farewell message 🚪',
    desc_members:     'List all members 👥',
    desc_setname:     'Change group name ✏️',
    desc_warn:        'Issue a warning ⚠️',
    desc_mode:        'Public / private mode 🔀',
    desc_settings:    'Bot settings panel ⚙️',
    desc_broadcast:   'Broadcast to all chats 📡',
    desc_block:       'Block a user 🚫',
    desc_unblock:     'Unblock a user ✅',
    desc_join:        'Join a group by link 🔗',
    desc_leave:       'Leave a group 🚶',
    desc_anticall:    'Auto-reject calls 📵',
    desc_antidelete:  'Recover deleted msgs 🗑️',
    desc_antiviewonce:'Save view-once media 👁️',
    desc_autoreact:   'Auto-react to msgs 😊',
    desc_autoreply:   'Auto-reply to msgs 💬',
    desc_autostatus:  'Auto-view statuses 👀',
    desc_ai:          'Ask AI anything 🤖',
    desc_gpt:         'ChatGPT responses 💡',
    desc_calc:        'Calculator 🔢',
    desc_translate:   'Translate text 🌍',
    desc_weather:     'Weather forecast ☀️',
    desc_wiki:        'Wikipedia search 📚',
    desc_sticker:     'Image → sticker 🖼️',
    desc_togif:       'Video → GIF 🎞️',
    desc_toimg:       'Sticker → image 🖼️',
    desc_tomp3:       'Video → MP3 🎵',
    desc_fact:        'Random interesting fact 💡',
    desc_joke:        'Tell a random joke 😂',
    desc_meme:        'Send a random meme 🤣',
    desc_alive:       'Check bot is alive 💚',
    desc_ping:        'Bot response speed ⚡',
    desc_owner:       'Contact the owner 👤',
    desc_runtime:     'Bot uptime info ⏱️',
    desc_lang:        'Change bot language 🌐',
    desc_save:        'Save a message 💾',
  },

  si: {
    // Main menu
    user:        'පරිශීලකයා',
    owner:       'හිමිකරු',
    prefix:      'උපසර්ගය',
    commands:    'විධාන',
    uptime:      'ක්‍රියාකාලය',
    ram:         'මතකය',
    categories:  'ප්‍රවර්ග',
    tapBtn:      'විධාන බලන්න පහත බොත්තමක් ක්ලික් කරන්න',
    cmdReady:    'විධාන සූදානම්',
    // Category titles
    cat_media:   'මාධ්‍ය සහ බාගත කිරීම්',
    cat_admin:   'පරිපාලක විධාන',
    cat_owner:   'හිමිකරු විධාන',
    cat_tools:   'මෙවලම් සහ AI',
    cat_general: 'සාමාන්‍ය සහ විනෝද',
    // Category labels (shown inside menu)
    cat_label_media:  'මාධ්‍ය සහ බාගත',
    cat_label_admin:  'කණ්ඩායම් Admin',
    cat_label_owner:  'හිමිකරු පමණක්',
    cat_label_tools:  'මෙවලම් සහ AI',
    cat_label_fun:    'විනෝද සහ සාමාන්‍ය',
    // Submenu
    backMenu:    '🔙 ප්‍රධාන මෙනුව',
    // Lang command
    currentLang: 'වත්මන් භාෂාව',
    selectLang:  'භාෂාව තෝරන්න',
    langChanged:  'භාෂාව වෙනස් විය',
    langInvalid: 'වලංගු නැත. .lang en, .lang si හෝ .lang pk භාවිත කරන්න',
    // Menu section text
    menu_bot_status:  'BOT තත්ත්වය',
    menu_total:       'මුළු',
    menu_cmds:        'විධාන',
    menu_tap:         '💡 විධාන බලන්න පහත බොත්තමක් ක්ලික් කරන්න',
    menu_type_help:   '🔖 `{prefix}<විධානය>` ටයිප් කර උදව් ලබාගන්න',
    cmds_available:   'විධාන ඇත',
    send_cmd_usage:   'ඕනෑම විධානයක් ලියා විස්තර ලබාගන්න',
    // Greetings
    greeting_morning:   '🌅 සුභ උදෑසනක්',
    greeting_afternoon: '☀️ සුභ දවසක්',
    greeting_evening:   '🌙 සුභ සන්ධ්‍යාවක්',
    // Alive command
    alive_greeting_1: 'හෙලෝ! මම ක්‍රියාත්මකව ඉන්නවා! 🚀',
    alive_greeting_2: 'ඔව්! Online හා සූදානම්! ⚡',
    alive_greeting_3: 'සුමටව ක්‍රියාත්මකයි! 🌟',
    alive_greeting_4: 'Bot ජීවතුන් අතර හා නිවැරදිව! 💫',
    alive_greeting_5: 'හෙලෝ! මම සක්‍රිය! 🎯',
    alive_status:     'තත්ත්වය',
    alive_online:     'Online',
    alive_status_lbl: 'තත්ත්වය',
    alive_uptime:     'ක්‍රියාකාලය',
    alive_owner:      'හිමිකරු',
    alive_prefix:     'උපසර්ගය',
    alive_version:    'සංස්කරණය',
    alive_type_menu:  '{prefix}menu ටයිප් කර විධාන බලන්න',
    alive_footer:     'කරන්නේ කුමක්ද?',
    alive_btn_menu:   '📋 ප්‍රධාන මෙනුව',
    alive_btn_ping:   '🏓 Ping පරීක්ෂා',
    // Ping command
    ping_title:     'Infinity MD තත්ත්වය',
    ping_local:     'දේශීය',
    ping_net:       'ජාල',
    ping_response:  'ප්‍රතිචාරය',
    ping_active:    'සක්‍රිය',
    ping_fast:      'වේගවත්',
    ping_normal:    'සාමාන්‍ය',
    ping_uptime:    'ක්‍රියාකාලය',
    ping_ram:       'RAM',
    ping_heap:      'Heap',
    ping_os:        'OS',
    ping_node:      'Node',
    ping_version:   'සංස්කරණය',
    ping_working:   '✨ සියල්ල නිවැරදිව ක්‍රියාත්මකයි!',
    ping_footer:    'සේවාදායක ස්වාස්ථ්‍යය',
    ping_btn_again: '🔄 නැවත Ping',
    ping_btn_menu:  '📋 මෙනුව',
    // Runtime command
    runtime_title:      'ක්‍රියාකාල තොරතුරු',
    runtime_bot_uptime: 'Bot ක්‍රියාකාලය',
    runtime_sys_uptime: 'පද්ධති ක්‍රියාකාලය',
    runtime_bot_mem:    'Bot මතකය',
    runtime_sys_mem:    'පද්ධති මතකය',
    runtime_cpu:        'CPU',
    runtime_cores:      'ශ්‍රේණි',
    runtime_used:       'යොදා ගත්',
    runtime_free:       'නිදහස්',
    runtime_external:   'External',
    runtime_hostname:   'Hostname',
    // Owner command
    owner_title:    'හිමිකරු තොරතුරු',
    owner_name:     'නම',
    owner_number:   'අංකය',
    owner_github:   'Github',
    // ── Command labels ──
    song:         'ගීතය බාගන්න',
    yt:           'YouTube සෙවීම',
    tiktok:       'TikTok බාගන්න',
    ytmp3:        'YouTube → MP3',
    ytmp4:        'YouTube → MP4',
    play:         'ඉක්මනින් වාදනය',
    lyrics:       'ගීත පද',
    movie:        'චිත්‍රපට සෙවීම',
    antilink:     'සබැඳි අවහිර',
    demote:       'Admin ඉවත් කරන්න',
    goodbye:      'සමුගැනීමේ පණිවිඩ',
    hidetag:      'නිහඬ ඇමතීම',
    kick:         'සාමාජිකයා ඉවත්',
    lock:         'කණ්ඩායම අගුළු',
    members:      'සාමාජිකයින් ලැයිස්තු',
    mute:         'කණ්ඩායම නිශ්ශබ්ද',
    promote:      'Admin කරන්න',
    setname:      'නම වෙනස් කරන්න',
    tagall:       'සියල්ලන්ට Tag',
    unlock:       'අගුළු අරින්න',
    unmute:       'නිශ්ශබ්දය ඉවත්',
    warn:         'අනතුරු ඇඟවීම',
    welcome:      'සාදරයෙන් පිළිගැනීම',
    anticall:     'ඇමතුම් අවහිර',
    antidelete:   'මකාදැමීම් අල්ලා',
    antiviewonce: 'viewonce සුරකින්න',
    autoreact:    'ස්වයං ප්‍රතිචාර',
    autoreply:    'ස්වයං පිළිතුරු',
    autostatus:   'ස්වයං status',
    block:        'පරිශීලකයා අවහිර',
    broadcast:    'සාමූහික පණිවිඩ',
    join:         'කණ්ඩායමට සම්බන්ධ',
    leave:        'කණ්ඩායම හැර යන්න',
    mode:         'Bot ක්‍රමය',
    settings:     'Bot සැකසීම්',
    unblock:      'අවහිරය ඉවත්',
    ai:           'AI සංවාදය',
    gpt:          'GPT සංවාදය',
    calc:         'ගණකය',
    sticker:      'Sticker සාදන්න',
    translate:    'පරිවර්තනය',
    weather:      'කාලගුණය',
    wiki:         'Wikipedia',
    togif:        'Video → GIF',
    toimg:        'Sticker → රූපය',
    tomp3:        'Video → MP3',
    fact:         'අහඹු කරුණ',
    joke:         'හාස්‍ය කතාව',
    meme:         'Meme රූපය',
    alive:        'Bot තත්ත්වය',
    ping:         'Ping Bot',
    owner:        'හිමිකරු තොරතුරු',
    runtime:      'පද්ධති සංඛ්‍යා',
    lang:         'භාෂාව වෙනස් කරන්න',
    save:         'Status සුරකින්න',
    // ── Command descriptions (shown in menu) ──
    desc_movie:       'Sinhalasub.lk චිත්‍රපට 🎬',
    desc_song:        'ගීත බාගන්න 🎵',
    desc_yt:          'YouTube සෙවීම 🔍',
    desc_ytmp3:       'YouTube → MP3 🎧',
    desc_ytmp4:       'YouTube → MP4 📹',
    desc_play:        'ශ්‍රව්‍යය වාදනය ▶️',
    desc_tiktok:      'TikTok බාගන්න 🎵',
    desc_lyrics:      'ගීත පද සොයන්න 🎤',
    desc_film2:       'CineSubz චිත්‍රපට & TV 🎬',
    desc_antilink:    'සබැඳි ස්වයංක්‍රීයව අවහිර 🔗',
    desc_tagall:      'සියලු සාමාජිකයින්ට Tag 📢',
    desc_hidetag:     'නිශ්ශබ්දව Tag 🔕',
    desc_kick:        'සාමාජිකයා ඉවත් 🦶',
    desc_promote:     'Admin කරන්න ⬆️',
    desc_demote:      'Admin ඉවත් ⬇️',
    desc_mute:        'කණ්ඩායම නිශ්ශබ්ද 🔇',
    desc_unmute:      'නිශ්ශබ්දය ඉවත් 🔊',
    desc_lock:        'කණ්ඩායම අගුළු 🔒',
    desc_unlock:      'කණ්ඩායම අගුළු අරින්න 🔓',
    desc_welcome:     'නව සාමාජිකයින්ට සාදරය 👋',
    desc_goodbye:     'සමුගැනීමේ පණිවිඩ 🚪',
    desc_members:     'සාමාජිකයින් ලැයිස්තු 👥',
    desc_setname:     'කණ්ඩායම් නම වෙනස් ✏️',
    desc_warn:        'අනතුරු ඇඟවීම ⚠️',
    desc_mode:        'ප්‍රසිද්ධ / පෞද්ගලික ක්‍රමය 🔀',
    desc_settings:    'Bot සැකසීම් 🖥️⚙️',
    desc_broadcast:   'සාමූහික පණිවිඩ 📡',
    desc_block:       'පරිශීලකයා අවහිර 🚫',
    desc_unblock:     'අවහිරය ඉවත් ✅',
    desc_join:        'සබැඳියෙන් කණ්ඩායමට 🔗',
    desc_leave:       'කණ්ඩායම හැර 🚶',
    desc_anticall:    'ඇමතුම් ස්වයංක්‍රීයව ප්‍රතික්ෂේප 📵',
    desc_antidelete:  'මකාදැමූ පණිවිඩ යළි ලබාගන්න 🗑️',
    desc_antiviewonce:'viewonce සුරකින්න 👁️',
    desc_autoreact:   'ස්වයං ප්‍රතිචාර 😊',
    desc_autoreply:   'ස්වයං පිළිතුරු 💬',
    desc_autostatus:  'ස්වයංක්‍රීයව Status බලන්න 👀',
    desc_ai:          'AI ගෙන් ඕනෑම දෙයක් 🤖',
    desc_gpt:         'ChatGPT 💡',
    desc_calc:        'ගණකය 🔢',
    desc_translate:   'පරිවර්තනය 🌍',
    desc_weather:     'කාලගුණ අනාවැකිය ☀️',
    desc_wiki:        'Wikipedia සෙවීම 📚',
    desc_sticker:     'රූපය → Sticker 🖼️',
    desc_togif:       'Video → GIF 🎞️',
    desc_toimg:       'Sticker → රූපය 🖼️',
    desc_tomp3:       'Video → MP3 🎵',
    desc_fact:        'අහඹු කරුණ 💡',
    desc_joke:        'හාස්‍ය කතාව 😂',
    desc_meme:        'Meme රූපය 🤣',
    desc_alive:       'Bot ජීවතුන් අතරදැයි 💚',
    desc_ping:        'Bot ප්‍රතිචාර වේගය ⚡',
    desc_owner:       'හිමිකරු ඇමතීම 👤',
    desc_runtime:     'Bot ක්‍රියාකාල තොරතුරු ⏱️',
    desc_lang:        'Bot භාෂාව වෙනස් 🌐',
    desc_save:        'Status සුරකින්න 💾',
  },

  pk: {
    // Main menu
    user:        'صارف',
    owner:       'مالک',
    prefix:      'سابقہ',
    commands:    'کمانڈز',
    uptime:      'چلنے کا وقت',
    ram:         'میموری',
    categories:  'زمرہ جات',
    tapBtn:      'کمانڈز دیکھنے کے لیے نیچے بٹن دبائیں',
    cmdReady:    'کمانڈز تیار',
    // Category titles
    cat_media:   'میڈیا اور ڈاؤنلوڈز',
    cat_admin:   'ایڈمن کمانڈز',
    cat_owner:   'مالک کمانڈز',
    cat_tools:   'ٹولز اور AI',
    cat_general: 'عام اور تفریح',
    // Category labels (shown inside menu)
    cat_label_media:  'میڈیا اور ڈاؤنلوڈ',
    cat_label_admin:  'گروپ ایڈمن',
    cat_label_owner:  'صرف مالک',
    cat_label_tools:  'ٹولز اور AI',
    cat_label_fun:    'تفریح اور عام',
    // Submenu
    backMenu:    '🔙 مین مینو',
    // Lang command
    currentLang: 'موجودہ زبان',
    selectLang:  'اپنی زبان منتخب کریں',
    langChanged: 'زبان تبدیل ہوگئی',
    langInvalid: 'غلط۔ استعمال کریں: .lang en، .lang si یا .lang pk',
    // Menu section text
    menu_bot_status:  'BOT کی حالت',
    menu_total:       'کل',
    menu_cmds:        'کمانڈز',
    menu_tap:         '💡 کمانڈز دیکھنے کے لیے نیچے بٹن دبائیں',
    menu_type_help:   '🔖 استعمال کے لیے `{prefix}<کمانڈ>` ٹائپ کریں',
    cmds_available:   'کمانڈز دستیاب',
    send_cmd_usage:   'تفصیل کے لیے کوئی بھی کمانڈ بھیجیں',
    // Greetings
    greeting_morning:   '🌅 صبح بخیر',
    greeting_afternoon: '☀️ دوپہر بخیر',
    greeting_evening:   '🌙 شام بخیر',
    // Alive command
    alive_greeting_1: 'ہیلو! میں چل رہا ہوں! 🚀',
    alive_greeting_2: 'ہاں، آن لائن اور تیار! ⚡',
    alive_greeting_3: 'بالکل ٹھیک چل رہا ہوں! 🌟',
    alive_greeting_4: 'Bot زندہ اور بالکل ٹھیک! 💫',
    alive_greeting_5: 'ہیلو! میں یہاں فعال ہوں! 🎯',
    alive_status:     'حالت',
    alive_online:     'آن لائن',
    alive_status_lbl: 'حالت',
    alive_uptime:     'چلنے کا وقت',
    alive_owner:      'مالک',
    alive_prefix:     'سابقہ',
    alive_version:    'ورژن',
    alive_type_menu:  '{prefix}menu ٹائپ کریں تمام کمانڈز دیکھیں',
    alive_footer:     'آپ کیا کرنا چاہتے ہیں؟',
    alive_btn_menu:   '📋 مین مینو',
    alive_btn_ping:   '🏓 پنگ ٹیسٹ',
    // Ping command
    ping_title:     'Infinity MD کی حالت',
    ping_local:     'مقامی',
    ping_net:       'نیٹ',
    ping_response:  'جواب',
    ping_active:    'فعال',
    ping_fast:      'تیز',
    ping_normal:    'عام',
    ping_uptime:    'چلنے کا وقت',
    ping_ram:       'RAM',
    ping_heap:      'Heap',
    ping_os:        'OS',
    ping_node:      'Node',
    ping_version:   'ورژن',
    ping_working:   '✨ سب کچھ بالکل ٹھیک!',
    ping_footer:    'سرور کی صحت',
    ping_btn_again: '🔄 دوبارہ پنگ',
    ping_btn_menu:  '📋 مینو',
    // Runtime command
    runtime_title:      'رن ٹائم معلومات',
    runtime_bot_uptime: 'Bot چلنے کا وقت',
    runtime_sys_uptime: 'سسٹم چلنے کا وقت',
    runtime_bot_mem:    'Bot میموری',
    runtime_sys_mem:    'سسٹم میموری',
    runtime_cpu:        'CPU',
    runtime_cores:      'کورز',
    runtime_used:       'استعمال',
    runtime_free:       'خالی',
    runtime_external:   'External',
    runtime_hostname:   'Hostname',
    // Owner command
    owner_title:    'مالک کی معلومات',
    owner_name:     'نام',
    owner_number:   'نمبر',
    owner_github:   'Github',
    // ── Command labels ──
    song:         'گانا ڈاؤنلوڈ',
    yt:           'YouTube تلاش',
    tiktok:       'TikTok ڈاؤنلوڈ',
    ytmp3:        'YouTube → MP3',
    ytmp4:        'YouTube → MP4',
    play:         'فوری چلائیں',
    lyrics:       'گانے کے بول',
    movie:        'فلم تلاش',
    antilink:     'لنک بلاک',
    demote:       'ایڈمن ہٹائیں',
    goodbye:      'الوداعی پیغام',
    hidetag:      'خاموش ذکر',
    kick:         'نکالیں',
    lock:         'گروپ لاک',
    members:      'ممبران کی فہرست',
    mute:         'گروپ خاموش',
    promote:      'ایڈمن بنائیں',
    setname:      'نام بدلیں',
    tagall:       'سب کو Tag',
    unlock:       'لاک کھولیں',
    unmute:       'خاموشی ہٹائیں',
    warn:         'وارننگ دیں',
    welcome:      'خوش آمدید پیغام',
    anticall:     'کال بلاک',
    antidelete:   'ڈیلیٹ پکڑیں',
    antiviewonce: 'viewonce محفوظ',
    autoreact:    'خودکار ری ایکٹ',
    autoreply:    'خودکار جواب',
    autostatus:   'خودکار status',
    block:        'صارف بلاک',
    broadcast:    'اجتماعی پیغام',
    join:         'گروپ جوائن',
    leave:        'گروپ چھوڑیں',
    mode:         'Bot موڈ',
    settings:     'Bot سیٹنگز',
    unblock:      'بلاک ہٹائیں',
    ai:           'AI چیٹ',
    gpt:          'GPT چیٹ',
    calc:         'کیلکولیٹر',
    sticker:      'Sticker بنائیں',
    translate:    'ترجمہ',
    weather:      'موسم',
    wiki:         'Wikipedia',
    togif:        'Video → GIF',
    toimg:        'Sticker → تصویر',
    tomp3:        'Video → MP3',
    fact:         'دلچسپ حقیقت',
    joke:         'مذاق',
    meme:         'Meme تصویر',
    alive:        'Bot کی حالت',
    ping:         'Ping Bot',
    owner:        'مالک کی معلومات',
    runtime:      'سسٹم اعداد',
    lang:         'زبان بدلیں',
    save:         'Status محفوظ کریں',
    // ── Command descriptions (shown in menu) ──
    desc_movie:       'فلم تلاش 🎬',
    desc_song:        'گانے ڈاؤنلوڈ 🎵',
    desc_yt:          'YouTube تلاش 🔍',
    desc_ytmp3:       'YouTube → MP3 🎧',
    desc_ytmp4:       'YouTube → MP4 📹',
    desc_play:        'آڈیو چلائیں ▶️',
    desc_tiktok:      'TikTok ڈاؤنلوڈ 🎵',
    desc_lyrics:      'گانے کے بول 🎤',
    desc_film2:       'CineSubz فلمیں اور TV 🎬',
    desc_antilink:    'گروپ لنک بلاک 🔗',
    desc_tagall:      'سب ممبران Tag 📢',
    desc_hidetag:     'خاموشی سے Tag 🔕',
    desc_kick:        'ممبر نکالیں 🦶',
    desc_promote:     'ایڈمن بنائیں ⬆️',
    desc_demote:      'ایڈمن ہٹائیں ⬇️',
    desc_mute:        'گروپ خاموش 🔇',
    desc_unmute:      'خاموشی ہٹائیں 🔊',
    desc_lock:        'گروپ لاک 🔒',
    desc_unlock:      'گروپ لاک کھولیں 🔓',
    desc_welcome:     'نئے ممبران کا خیرمقدم 👋',
    desc_goodbye:     'الوداعی پیغام 🚪',
    desc_members:     'ممبران کی فہرست 👥',
    desc_setname:     'گروپ نام بدلیں ✏️',
    desc_warn:        'وارننگ دیں ⚠️',
    desc_mode:        'عام / نجی موڈ 🔀',
    desc_settings:    'Bot سیٹنگز ⚙️',
    desc_broadcast:   'اجتماعی پیغام 📡',
    desc_block:       'صارف بلاک 🚫',
    desc_unblock:     'بلاک ہٹائیں ✅',
    desc_join:        'لنک سے گروپ جوائن 🔗',
    desc_leave:       'گروپ چھوڑیں 🚶',
    desc_anticall:    'کال خودکار رد 📵',
    desc_antidelete:  'مٹائے پیغام واپس 🗑️',
    desc_antiviewonce:'view-once میڈیا محفوظ 👁️',
    desc_autoreact:   'خودکار ری ایکٹ 😊',
    desc_autoreply:   'خودکار جواب 💬',
    desc_autostatus:  'خودکار status دیکھیں 👀',
    desc_ai:          'AI سے کچھ بھی پوچھیں 🤖',
    desc_gpt:         'ChatGPT جوابات 💡',
    desc_calc:        'کیلکولیٹر 🔢',
    desc_translate:   'ترجمہ کریں 🌍',
    desc_weather:     'موسم کی پیشگوئی ☀️',
    desc_wiki:        'Wikipedia تلاش 📚',
    desc_sticker:     'تصویر → Sticker 🖼️',
    desc_togif:       'Video → GIF 🎞️',
    desc_toimg:       'Sticker → تصویر 🖼️',
    desc_tomp3:       'Video → MP3 🎵',
    desc_fact:        'دلچسپ حقیقت 💡',
    desc_joke:        'مذاق سنائیں 😂',
    desc_meme:        'Meme تصویر 🤣',
    desc_alive:       'Bot زندہ ہے؟ 💚',
    desc_ping:        'Bot جواب کی رفتار ⚡',
    desc_owner:       'مالک سے رابطہ 👤',
    desc_runtime:     'Bot چلنے کا وقت ⏱️',
    desc_lang:        'Bot زبان بدلیں 🌐',
    desc_save:        'پیغام محفوظ کریں 💾',
  },
};

function getLang(chatId) {
  return chatLangMap.get(String(chatId)) || 'en';
}

function setLang(chatId, lang) {
  if (!LANGUAGES[lang]) return false;
  chatLangMap.set(String(chatId), lang);
  return true;
}

/** Translate a key for the given language, falling back to English. */
function t(key, lang) {
  const l = LANGUAGES[lang] ? lang : 'en';
  return STRINGS[l][key] ?? STRINGS.en[key] ?? key;
}

module.exports = { getLang, setLang, t, LANGUAGES };
